# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JuiceMaker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JuiceMaker
  pod 'RxSwift'
  pod 'RxCocoa'
  target 'JuiceMakerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
